---
apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
  name: local-disks
  namespace: openshift-local-storage
spec:
  managementState: Managed
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
        - key: ran.openshift.io/lso
          operator: Exists
  storageClassDevices:
    - storageClassName: "lso-filesystemclass"
      volumeMode: Filesystem
      fsType: xfs
      devicePaths:
        - /dev/autopart/lv_1
        - /dev/autopart/lv_2
        - /dev/autopart/lv_3
        - /dev/autopart/lv_4
    - storageClassName: "lso-blockclass"
      volumeMode: Block
      devicePaths:
        - /dev/autopart/lv_5
        - /dev/autopart/lv_6
        - /dev/autopart/lv_7
        - /dev/autopart/lv_8
