---
apiVersion: v1
kind: Secret
metadata:
  name: bmc-super1-volante-cars-lab
  namespace: volante-cars-lab
data:
  username: cm9vdA==
  password: YWx0aW9zdGFyMTIz
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: bmc-super2-volante-cars-lab
  namespace: volante-cars-lab
data:
  username: cm9vdA==
  password: YWx0aW9zdGFyMTIz
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: bmc-super3-volante-cars-lab
  namespace: volante-cars-lab
data:
  username: cm9vdA==
  password: YWx0aW9zdGFyMTIz
type: Opaque
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: super1-volante-cars-lab
  namespace: volante-cars-lab
  labels:
    infraenvs.agent-install.openshift.io: "infraenv-volante-cars-lab"
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "super1"
    bmac.agent-install.openshift.io/role: master
    bmac.agent-install.openshift.io/installer-args: '["--copy-network"]'
spec:
  online: true
  bootMACAddress: DE:AD:BE:EF:77:DA
  automatedCleaningMode: disabled
  bmc:
    address: redfish-virtualmedia+https://kvmhost2.remote-skylark-ldc1.cars.lab:8082/redfish/v1/Systems/2a143c67-0ad4-5522-9943-ecaeb27f4b43
    credentialsName: bmc-super1-volante-cars-lab
    disableCertificateVerification: True
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: super2-volante-cars-lab
  namespace: volante-cars-lab
  labels:
    infraenvs.agent-install.openshift.io: "infraenv-volante-cars-lab"
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "super2"
    bmac.agent-install.openshift.io/role: master
    bmac.agent-install.openshift.io/installer-args: '["--copy-network"]'
spec:
  online: true
  bootMACAddress: DE:AD:BE:EF:D0:D7
  automatedCleaningMode: disabled
  bmc:
    address: redfish-virtualmedia+https://kvmhost2.remote-skylark-ldc1.cars.lab:8082/redfish/v1/Systems/76721040-1e6a-5724-a863-4c3acf41af75
    credentialsName: bmc-super2-volante-cars-lab
    disableCertificateVerification: True
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: super3-volante-cars-lab
  namespace: volante-cars-lab
  labels:
    infraenvs.agent-install.openshift.io: "infraenv-volante-cars-lab"
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "super3"
    bmac.agent-install.openshift.io/role: master
    bmac.agent-install.openshift.io/installer-args: '["--copy-network"]'
spec:
  online: true
  bootMACAddress: DE:AD:BE:EF:A7:53
  automatedCleaningMode: disabled
  bmc:
    address: redfish-virtualmedia+https://kvmhost2.remote-skylark-ldc1.cars.lab:8082/redfish/v1/Systems/550e75a5-e224-5f1a-9a00-c132cea6f533
    credentialsName: bmc-super3-volante-cars-lab
    disableCertificateVerification: True
