---
###############################################################################
# specific resourceName for it (eg. sriov-netdevice-smci00)
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: ldc1-sriov-netdevice-smci02
  namespace: openshift-sriov-network-operator
spec:
  resourceName: vran_netdevice
  nodeSelector:
    ran.openshift.io/sriov: ""
    ran.openshift.io/ldc1-sriov-netdevice-smci02: ""
  deviceType: netdevice
  priority: 10
  #mtu: 1500
  numVfs: 10
  nicSelector:
    vendor: "8086"
    deviceID: "158b"
    pfNames:
      - enp81s0f0#0-3
---
###############################################################################
# specific resourceName for it (eg. sriov-vfio-smci00)
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: ldc1-sriov-vfio-ar-smci02
  namespace: openshift-sriov-network-operator
spec:
  resourceName: vran_vfio_ar
  nodeSelector:
    ran.openshift.io/sriov: ""
    ran.openshift.io/ldc1-sriov-vfio-smci02: ""
  deviceType: vfio-pci
  priority: 10
  #mtu: 1500
  numVfs: 10
  nicSelector:
    vendor: "8086"
    deviceID: "158b"
    pfNames:
      - enp81s0f0#4-5
---
###############################################################################
# specific resourceName for it (eg. sriov-vfio-smci00)
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: ldc1-sriov-vfio-smci02
  namespace: openshift-sriov-network-operator
spec:
  resourceName: vran_vfio
  nodeSelector:
    ran.openshift.io/sriov: ""
    ran.openshift.io/ldc1-sriov-vfio-smci02: ""
  deviceType: vfio-pci
  priority: 10
  #mtu: 1500
  numVfs: 10
  nicSelector:
    vendor: "8086"
    deviceID: "158b"
    pfNames:
      - enp81s0f0#6-7
---
###############################################################################
# specific resourceName for it (eg. sriov-netdevice-fh-smci00)
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: ldc1-sriov-netdevice-fh-smci02
  namespace: openshift-sriov-network-operator
spec:
  resourceName: vran_netdevice_fh
  nodeSelector:
    ran.openshift.io/sriov: ""
    ran.openshift.io/ldc1-sriov-netdevice-fh-smci02: ""
  deviceType: netdevice
  priority: 10
  #mtu: 1500
  numVfs: 10
  nicSelector:
    vendor: "8086"
    deviceID: "158b"
    pfNames:
      - enp81s0f0#8-9
