# Validate CPU topology
# $ for file in /sys/devices/system/cpu/cpu[0-9]*/topology/thread_siblings_list; do echo -n "$file "; cat $file; done |sort -k2 -n
# Supermicro with 1x Intel Ice Lake 6338R
---
apiVersion: performance.openshift.io/v2
kind: PerformanceProfile
metadata:
  name: ran-du-ldc1-smci01-profile0
spec:
  additionalKernelArgs:
  - rcupdate.rcu_normal_after_boot=0
  - crashkernel=512M
  - nohz=off
  - nohz_full=3-31,35-63 
  - slub_debug=FZPU
  cpu:
    isolated: 3-31,35-63
    reserved: 0-2,32-34
  net:
    userLevelNetworking: true
    devices:
    # intel I350
    - interfaceName: eno*
    # intel X550
    - interfaceName: enp25s0*
    # intel e810
    - interfaceName: enp138s0*
  hugepages:
    defaultHugepagesSize: "1G"
    pages:
    - size: "1G"
      count: 16
      node: 0
  numa:
    topologyPolicy: best-effort
  realTimeKernel:
    enabled: false
  nodeSelector:
    node-role.kubernetes.io/ran-du-ldc1-smci01: ""
