---
###############################################################################
# SR-IOV Network Definition for the NS of the workload
# vran-mh + vlan 806 + vran_netdevice
###############################################################################
# NS = workload-4g-du-ldc1-smci03
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: ldc1-vran-mh
  namespace: openshift-sriov-network-operator
spec:
  resourceName: vran_netdevice
  networkNamespace: workload-4g-du-ldc1-smci03
  vlan: 806
  ipam: |-
    {"type": "static"}
  linkState: auto
  # spoofChk: "<spoof_check>"
  # maxTxRate: <max_tx_rate>
  # minTxRate: <min_rx_rate>
  # vlanQoS: <vlan_qos>
  # trust: "<trust_vf>"
  # capabilities: <capabilities>
